"""add upstream events

Revision ID: be1fc5cfc23d
Revises: a7d214a64781
Create Date: 2026-09-11 21:06:12.889190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1fc5cfc23d'
down_revision = 'a7d214a64781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upstream_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('previous_sha', sa.String(length=40), nullable=False),
    sa.Column('current_sha', sa.String(length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upstream_events')
    # ### end Alembic commands ###
